version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    assignees:
      - "jboolean"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    assignees:
      - "jboolean"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    assignees:
      - "jboolean"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    assignees:
      - "jboolean"
  # - package-ecosystem: "npm"
  #   directory: "/edge"
  #   schedule:
  #     interval: "weekly"
  #     day: "saturday"
  #     time: "09:00"
  #     timezone: "America/New_York"
  #   assignees:
  #     - "jboolean"
