name: backend-pr
on:
  pull_request:
    paths-ignore:
      - "backend/**"

jobs:
  dryDeploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
  types:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '