name: backend-deploy-manual
on:
  workflow_dispatch:
    inputs:
      stage:
        description: Stage
        required: true
        default: 'staging'
        type: choice
        options:
          - production
          - staging
      frontendBaseUrl:
        description: Frontend Base URL
        required: false
        default: 'https://staging.1940s.nyc'
        type: string
defaults:
  run:
    shell: bash
    working-directory: backend
jobs:
  deployManual:
    uses: ./.github/workflows/backend-deploy-reusable.yml
    with:
      stage: ${{ inputs.stage }}
      frontendBaseUrl: ${{ inputs.frontendBaseUrl }}
    secrets: inherit