name: backend-deploy
on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
    
defaults:
  run:
    shell: bash
    working-directory: backend
jobs:
  deployStaging:
    uses: ./.github/workflows/backend-deploy-reusable.yml
    with:
      stage: staging
    secrets: inherit
  deployProduction:
    uses: ./.github/workflows/backend-deploy-reusable.yml
    with:
      stage: production
    secrets: inherit
    needs: deployStaging