name: backend-deploy
on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
defaults:
  run:
    shell: bash
    working-directory: backend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - name: Decrypt secrets
        env:
          SERVERLESS_SECRETS_PASSWORD: ${{ secrets.SERVERLESS_SECRETS_PASSWORD}}
        run: npx serverless decrypt --stage production --password "$SERVERLESS_SECRETS_PASSWORD"
      - name: Lint
        run: npm run lint:strict
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        run: npm run deploy