name: clone-db
on:
  workflow_dispatch:
    
defaults:
  run:
    shell: bash
    working-directory: backend
jobs:
  cloneDb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Copy data 
        run: ./cloneDb.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1